# Ускоренные градиентные методы

## Функция $f(x) = x_1^2 +x_2^2+x_1+x_2$, точка $x^{(0)} = (0, 0)$

In [1]:
import numpy as np

In [2]:
def f(x):
    return x[0]**2+x[1]**2+x[0]+x[1]
def grad_f(x):
    return np.array([2*x[0]+1, 2*x[1]+1])
def matrix_d2f(x):
    return np.array([[2, 0], [0, 2]])

### Ускоренный градиентный метод p-го порядка

In [3]:
a, b, eps = 0.0001, 0.9999,  0.005
def passive_search(x, grad, a = a, b = b, eps = eps):
    
    n = round((b-a)/eps)+1
    x_s = [a+i*eps for i in range(n)]
    y_s = [f(x-i*grad) for i in x_s]
    res = y_s.index(min(y_s))
    return x_s[res]

In [4]:
def grad_method_p(x = np.array([0, 0]), p = 2, alpha = 0.001, epsilon = 0.05):
    grad = grad_f(x)
    x1=x
    n = 0
    check = 0
    while (np.linalg.norm(grad) > epsilon) or (check < 3):
        for i in range(p):
            alp = passive_search(x1, grad)
            x1 = x1 - alp*grad
            grad = grad_f(x1)
        alpha = passive_search(x, x1-x)
        x = x + alpha*(x1-x)
        grad = grad_f(x)
        n+=1
        if (np.linalg.norm(grad) <= epsilon): check +=1
    print("Ускоренный градиентный метод {}-го порядка выполнил {} шагов".format(p, n))
    print("Точка с координатами х1 = {}, x2 = {}".format(x[0], x[1]))
    return x

In [5]:
%%time 
grad_method_p()

Ускоренный градиентный метод 2-го порядка выполнил 33424 шагов
Точка с координатами х1 = -0.4823269461015969, x2 = -0.4823269461015969
Wall time: 50.6 s


array([-0.48232695, -0.48232695])

### Овражный метод

In [6]:
def gully_method(x1 = np.array([0, 0]), alpha = 0.001, epsilon = 0.05, n_steps = 1, neigh = np.array([0.00001, 0.00001])):
    x2 = x1 + neigh
    grad1 = grad_f(x1)
    grad2 = grad_f(x2)
    n = 0
    check = 0
    while (np.linalg.norm(grad1) > epsilon) or (check < 3):
        for i in range(n_steps):
            x1 = x1 - alpha*grad1
            grad1 = grad_f(x1)
            x2= x2 - alpha*grad2
            grad2 = grad_f(x2)
        alp = passive_search(x1, x2-x1)
        x1 = x1 + alp*(x2-x1)
        grad1 = grad_f(x1)
        x2 = x1 + neigh
        grad2 = grad_f(x2)
        n+=1
        if (np.linalg.norm(grad1) <= epsilon): check +=1
    print("Овражный метод выполнил {} шагов".format( n))
    print("Точка с координатами х1 = {}, x2 = {}".format(x1[0], x1[1]))
    return x1

In [7]:
%%time
gully_method()

Овражный метод выполнил 1833 шагов
Точка с координатами х1 = -0.4823942552714334, x2 = -0.4823942552714334
Wall time: 948 ms


array([-0.48239426, -0.48239426])

### Метод Ньютона

In [8]:
def newton_method(x = np.array([0, 0]), epsilon = 0.05):
    d2f = matrix_d2f(x)
    d2f_inv = np.linalg.inv(d2f)
    direction = d2f_inv @ np.transpose(grad_f(x))
    alpha = passive_search(x, direction)
    return x - alpha * direction

In [9]:
%%time
newton_method()

Wall time: 2 ms


array([-0.50005, -0.50005])